name: typed_cache
description: A strongly-typed, generic caching library for Dart.
version: 0.3.0
repository: https://github.com/saulogatti/typed_cache.git
environment:
  sdk: ^3.10.4

dependencies:
  meta: ^1.10.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
